# Generated by Django 4.2.13 on 2024-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MesaAyuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='cas_estado',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada')], db_comment='Eleccion del estado del caso', default='Solicitada', max_length=15),
        ),
    ]
